# Generated by Django 4.0.3 on 2022-04-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('result', models.IntegerField()),
                ('happiness', models.IntegerField(default=0)),
                ('angry', models.IntegerField(default=0)),
                ('disgust', models.IntegerField(default=0)),
                ('fear', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('sadness', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
