# Generated by Django 4.0.3 on 2022-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_created_at_diary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
