# Generated by Django 4.0.3 on 2022-04-10 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=10)),
                ('happiness', models.IntegerField(default=0)),
                ('angry', models.IntegerField(default=0)),
                ('disgust', models.IntegerField(default=0)),
                ('fear', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('sadness', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
